name: actipy_env

channels:
    - defaults
    - conda-forge
dependencies:
- python == 3.12.0
- python.app
- numpy == 1.26
- pandas == 2.2.3
- matplotlib == 3.9.2
- seaborn == 0.13.2
- ipykernel == 6.29.5
- pingouin == 0.5.5
- astropy == 6.1.4
- notedown == 1.5.1
- autopep8 == 2.3.1
- pip
- pip:
  - memspectrum  
  - jedi 
  - parso
  - git+https://github.com/aa-fisk/sleepPy.git@main

